### ISSUE TITLE
Error reading from XML stream

### ISSUE THREAD

**Issue by minhnhb** [fritzy/SleekXMPP#101]
2011-09-12 15:49:21    4194      ERROR     sleekxmpp.xmlstream.xmlstream    Error reading from XML stream.

I received this log frequently but don't know what is happening. Anyone can explain it for me, please?

**Comment by fritzy** [comment]
This happens when cElementTree.ElementTree.iterparse raises a SyntaxError, or in other worse, when you receive invalid XML.

**Comment by ayanamist** [comment]
@fritzy Sorry, but it seems 1.0 stable version still has such issue.
`sleekxmpp.basexmpp ERROR    no element found: line 1, column 100091
Traceback (most recent call last):
  File "/home/dotcloud/env/lib/python2.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1150, in _process
    if not self.__read_xml():
  File "/home/dotcloud/env/lib/python2.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1186, in __read_xml
    for event, xml in ET.iterparse(self.filesocket, (b'end', b'start')):
  File "<string>", line 68, in __iter__
SyntaxError: no element found: line 1, column 100091`

**Comment by minhnhb** [comment]
Hi, are you guys using Openfire server? If so, update to the latest version.

**Comment by ayanamist** [comment]
@minhnhb The client is connecting to GTalk server.

**Comment by legastero** [comment]
The root cause of the issue is that GTalk will frequently just end the connection without sending a closing `</stream:stream>` tag.

This should just be a logging issue now - the exception _is_ handled, but the exception handler in BaseXMPP in 1.0 prints the exception traceback anyway. That has been fixed in the develop branch.

[Exception caught](https://github.com/fritzy/SleekXMPP/blob/master/sleekxmpp/xmlstream/xmlstream.py#L1163)
[BaseXMPP dumps exception log](https://github.com/fritzy/SleekXMPP/blob/master/sleekxmpp/basexmpp.py#L767)

**Comment by ayanamist** [comment]
@legastero However, I have set auto_reconnect=True, but the client disconnects and never connect again. I don't think it's handled correctly.

**Comment by legastero** [comment]
@ayanamist Ah, the SyntaxError except block was incorrectly instructing Sleek to shutdown completely (like when handling the SystemExit, etc exceptions). The develop branch fixes that now.
