### ISSUE TITLE
Can't configure muc room

### ISSUE THREAD

**Issue by minhnhb** [fritzy/SleekXMPP#107]
I want to create a muc room from a component and here is my approach:
1. Send a muc presence
   xep_0045.joinMUC(room, nick, wait=True)
2. Configure room
   xep_0045.configureRoom(room)

As you know, firstly, configureRoom() call getRoomForm(), but this function failed to get the form because of timeout.

Is there anyone know what's wrong with it? I'm using Openfire v3.7.1.

**Comment by minhnhb** [comment]
It's ok to create a room from a client.

**Comment by legastero** [comment]
Components must always specify the JID they are using when sending stanzas because they are allowed to use multiple JIDs. My guess is that the issue is occurring because you are not specifying ifrom='somejid@yourcomponent.server' to your configureRoom request.

Also, I just checked and it looks like joinMUC is lacking a way to specify the sending JID, so I'll add that now in the develop branch.

So, once that is patched I would expect the following to work:
1. xep_0045.joinMUC(room, nick, wait=True, pfrom='somejid@component.server')
2. xep_0045.configureRoom(room, ifrom='somejid@component.server')

**Comment by minhnhb** [comment]
@legastero:  Many thanks! It's now working perfectly.
