### ISSUE TITLE
External DB backend for roster

### ISSUE THREAD

**Issue by coffeeowl** [fritzy/SleekXMPP#117]
I am trying to attach Mongo DB I already have to Roster. RosterItem says I have to implement two methods - load and save. Looks like it is not enough, because Roster.set_backend tries to access 'entries' on my class. 

```
def set_backend(self, db=None):
    """
    Set the datastore interface object for the roster.

    Arguments:
        db -- The new datastore interface.
    """
    self.db = db
    for node in self.db.entries(None, {}):
        self.add(node)
    for node in self._rosters:
        self._rosters[node].set_backend(db)
```

Also, what will happen if I invoke this method with default arg for 'db'? I think it will fail, as None can't have 'entries' property.

**Comment by legastero** [comment]
Ah, right. The entries() method needs to go in that doc section too. Here is what that method is supposed to do: given the owner JID for a roster, return all of the item JIDs for it, or if no JID is given return all of the owner JIDs for the multiple rosters.

As for the default None value, `db` really shouldn't be optional so that will be fixed.

You can see how I made a Redis backend here: https://github.com/legastero/SleekRedis/blob/master/redis_roster.py

**Comment by coffeeowl** [comment]
OK, thanks.
