### ISSUE TITLE
meth: send in xmlstream.py 

### ISSUE THREAD

**Issue by leopay** [fritzy/SleekXMPP#158]
Parameter `mask` in send method is emphasized as DEPRECATED
Does it mean the feature `Execution will block in this thread until the response is received or a timeout occurs` may not be supported in the future?

**Comment by legastero** [comment]
Yes, the `mask` parameter is deprecated because it only allows use of a MatchXMLMask matcher. It may in a future version be replaced with a different parameter.

The current preferred and more generic method is to use:

```
# matcher is a MatchXMLMask, MatchXPath, StanzaPath, or MatcherId object
# self is the ClientXMPP/ComponentXMPP instance
waiter = Waiter('unique name', matcher, self)
response = waiter.wait()
```

However, with both the deprecated `mask` and the above, execution will block in the current thread (this happens with the `wait()` method).

**Comment by leopay** [comment]
ths
