### ISSUE TITLE
Auto-Reconnect State

### ISSUE THREAD

**Issue by fritzy** [fritzy/SleekXMPP#20]
I suspect that auto-reconnect currently puts SleekXMPP in a bad state. I need to investigate and fix this if necessary.

**Comment by macdiesel** [comment]
I have seen this behavior as well when I kill a client from the server side.  Here is some of the output from the console:
INFO     Reconnecting
DEBUG    Since no address is supplied, attempting SRV lookup.
DEBUG    No appropriate SRV record found.  Using JID server name.
WARNING  Failed to connect
Traceback (most recent call last):
DEBUG    SEND: <stream:stream to='macdiesel-desktop' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' version='1.0'>
  File "/home/macdiesel/tmp/workspace/SleekXMPP/sleekxmpp/xmlstream/xmlstream.py", line 171, in _process
WARNING  Failed to send <stream:stream to='macdiesel-desktop' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' version='1.0'>
ERROR    Disconnected. Socket Error.
Traceback (most recent call last):
  File "/home/macdiesel/tmp/workspace/SleekXMPP/sleekxmpp/xmlstream/xmlstream.py", line 245, in _sendThread
    while self.run and self.__readXML():
  File "/home/macdiesel/tmp/workspace/SleekXMPP/sleekxmpp/xmlstream/xmlstream.py", line 217, in __readXML
    for (event, xmlobj) in cElementTree.iterparse(self.filesocket, (b'end', b'start')):
  File "<string>", line 61, in __iter__
  File "/home/macdiesel/tmp/workspace/SleekXMPP/sleekxmpp/xmlstream/filesocket.py", line 14, in read
    self.socket.send(data.encode('utf-8'))
  File "/usr/local/lib/python2.6/socket.py", line 165, in _dummy
    data = self._sock.recv(size)
AttributeError: 'NoneType' object has no attribute 'recv'
INFO     Reconnecting
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor
DEBUG    Quitting eventRunner thread
DEBUG    Since no address is supplied, attempting SRV lookup.
DEBUG    No appropriate SRV record found.  Using JID server name.
DEBUG    SEND: <stream:stream to='macdiesel-desktop' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' version='1.0'>
DEBUG    RECV: <ns0:features xmlns:ns0="http://etherx.jabber.org/streams"><ns1:starttls xmlns:ns1="urn:ietf:params:xml:ns:xmpp-tls" /><ns1:mechanisms xmlns:ns1="urn:ietf:params:xml:ns:xmpp-sasl">ns1:mechanismPLAIN/ns1:mechanismns1:mechanismCRAM-MD5/ns1:mechanismns1:mechanismANONYMOUS/ns1:mechanismns1:mechanismDIGEST-MD5/ns1:mechanism/ns1:mechanisms<ns1:compression xmlns:ns1="http://jabber.org/features/compress">ns1:methodzlib/ns1:method/ns1:compression<ns1:auth xmlns:ns1="http://jabber.org/features/iq-auth" /><ns1:register xmlns:ns1="http://jabber.org/features/iq-register" />/ns0:features

**Comment by macdiesel** [comment]
I made some modifications to hopefully fix this issue if you could review them when you have a moment.

http://github.com/macdiesel/SleekXMPP/commit/70f69c180cb828f0a76b0d9a441c98036cc96fb0

**Comment by fritzy** [comment]
Fixed
