### ISSUE TITLE
Support python-3.3

### ISSUE THREAD

**Issue by Nikoli** [fritzy/SleekXMPP#264]
Please add support for python-3.3, it will be used in Gentoo by default instead of python-3.3 soon:
https://bugs.gentoo.org/show_bug.cgi?id=474128

**Comment by Nikoli** [comment]
Is something blocking it?

**Comment by mathieui** [comment]
The trunk version has been supporting 3.3 for quite a while, and I am currently running an XMPP client using sleek with no issue. (although the test suite does not currently work because some XEPs e.g. 0323 have been written exclusively for python2, it seems)

The issue, I guess, has more to do with the fact that the last release was a long time ago. (“SleekXMPP is an MIT licensed XMPP library for Python 2.6/3.1+”, 3.3 being covered by 3.1+ as far as I am aware)

**Comment by Nikoli** [comment]
setup.py still does not have `'Programming Language :: Python :: 3.3',`

**Comment by legastero** [comment]
Added that line to setup.py
