### ISSUE TITLE
Stream Feature workflow sucks in ClientXMPP

### ISSUE THREAD

**Issue by fritzy** [fritzy/SleekXMPP#39]
The stream workflow is not intuitive in ClientXMPP, and is prone to ordering bugs. This needs to be re-factored.

8 points

**Comment by fritzy** [comment]
There are a few issues here.  Some servers offer features that contextually don't make any sense at all (offering tls after tls is already negotiated) and sometimes we want to prioritize features (bind before session, tls before compress).

**Comment by thom-nic** [comment]
I think the easiest way to solve this problem might be to make the auth, session & bind negotiation all occur synchronously before the read, process, event threads are even started.  Then you have direct and fine-grained control over what happens and at any point it is easy to determine what should happen next (e.g. bind comes before session) and at any point if the server doesn't behave as expected it's easy to close the socket and start over.  

I mention this because I've noticed situations where the client never gets the features stanza from the server, or some other response during negotiation and as a result the client just sits and waits indefinitely.  Since this stuff if really part of session establishment, it really should have a 'timeout' which kills and restarts the socket for any case when the session isn't established w/in so many seconds.  

I suppose it's not 'easy' to do it this way since it would involve pulling logic from the read thread & others.  But I thought I'd mention it since we've definitely seen some odd behavior that seemed to result from session negotiation being handled asynchronously.  Honestly I'm not sure what the 'best' way would be, but I've looked at the Java Smack XMPP library that they appear to do all pre-session negotiation synchronously.

**Comment by thom-nic** [comment]
Another option would be (as I alluded to above) to be able to 'timeout' if an expected stanza isn't received w/in a certain amount of time.  This would probably be useful in the general case (for IQ requests that don't respond) -- is it already implemented and could it be re-used?  

As for prioritizing features -- you have all of the feature handlers in some sort of collection, right? (I don't recall w/o digging through the code.)  Could you use an ordered collection to dictate priority?  e.g. first feature handler in the list that matches gets executed.  I also seem to remember the XMPP RFC mentioning something about the order of features in the stanza sent from the server.

**Comment by fritzy** [comment]
Ultimately, I don't want to disrupt the system as it stands now, but getting to jid binding should definitely be a timeout event in session negotiation! This definitely has to be in 1.0.

**Comment by fritzy** [comment]
What I'll likely do is remove feature handlers.  This was put in place to make it easy for others to support stream features, but the pain in dependencies isn't worth the gain. Especially since stream features often require extending xmlstream anyway. A simple handler for stream:features will clean this right up.

**Comment by legastero** [comment]
Beta6 cleans all of this up rather nicely, so let's close this.
