### ISSUE TITLE
Refactor state machine.

### ISSUE THREAD

**Issue by fritzy** [fritzy/SleekXMPP#42]
tomstrummer has done a lot of refactoring in order to create a solid state machine.  This should fix a lot of bugs, but needs to be audited.

**Comment by fritzy** [comment]
This is mine, and not part of the hackfest.

**Comment by macdiesel** [comment]
digest-md5 support is also mashed in with the state machine changes as well.

**Comment by fritzy** [comment]
right, macdiesel has another fork with state machine refactoring I need to review.  I guess I need to pick one.

digest-md5 will be in 1.1, likely with http://github.com/dwd/Suelta

**Comment by macdiesel** [comment]
Tom and I work for the same company and have been pulling eachothers branches. The state machine is the same.

**Comment by fritzy** [comment]
Oh! I need to get more sleep.  ;)  thanks guys!

**Comment by fritzy** [comment]
the tommerge branch was an experiment to review all of the tomstrummer patches, and generally I liked the cleanup and approach. I'll be taking a lot of ideas from tomstrummer and macdiesel's fork and I'll try to find a way to give them credit, but I won't be taking the patches directly. I want to keep SleekXMPP very easy to read, and their cleanup is nice for that, but the state machine itself is a bit harder to follow for a newcomer and doesn't fulfill the purpose of managing current state.

**Comment by thom-nic** [comment]
The state machine isn't responsible for 'managing' the entire state of the system (objects do that) but it does attempt to manage atomic changes to some of those properties that interact with multiple threads.  I'd argue that the state machine _does_ in fact manage those critical pieces of state correctly by avoiding the race conditions that were cropping up before.  

The state machine paradigm (http://en.wikipedia.org/wiki/Finite_state_machine) has some well-defined characteristics like guards and atomic transitions which my class tries to model in a fairly straightforward manner.  Unfortunately parallelism is a notoriously difficult problem in computer science and the nature of the problem necessitates some amount of complexity.  If there's a simpler way to synchronize state between threads that's great, but I'd be wary of sacrificing correctness in the name of simplicity.  Sure, you could use a lock or condition around operations like connectTCP (instead of using a state machine,) but that's essentially what the state machine does, and it actually hides some of that complexity :)  StateMachine.transition() and ensure() very clearly indicate what they're doing (at least if you understand the state machine paradigm) and guarantee that those operations are thread-safe and atomic.

If your state machine model needs to be more complex (maybe disconnected-> connected-> session_started) it's easy enough to add new states.  Some of the boolean variables that are still used in basexmpp and xmlstream could be rolled into the state machine but they weren't critical to synchronizing operations between multiple threads.  

As an aside, I also noticed that boolean variables in Python don't seem to behave as 'volatile,' e.g. a change in value from one thread doesn't seem to be immediately picked up from another thread.  (Accessing the value from a dict seems to circumvent this.)  In those situations where a boolean _is_ accessed from multiple threads, It's probably more appropriate to use Python's threading.Event class instead.  This also allows threads that _are_ synchronizing on boolean value to wait() without polling and be notified when the value is set.

**Comment by thom-nic** [comment]
That said, I was pretty heavy-handed in my refactoring, so kudos for actually merging it into your codebase :)  I'll browse through your merge over the next couple days.

**Comment by macdiesel** [comment]
Fritzy, for what what it's worth a lot of man hours went into repairing the state machine.  It was a very complex problem to solve as there were/are many threads trying to invoke the same code at the same time.  With concurrency problems such as this there usually is some level of complexity that is gained, however I do feel that the majority of the changes, that Tom made, end up actually being a pretty simple solution to a difficult problem. As Tom has pointed out the state machine can be expanded further if necessary, though I'm not totally sold on the fact that it needs to be.  We have been talking about adding some additional events that could be fired that could be used if other threads or methods needed to know about the current state of the connection.  This would allow the state machine to remain simple (or perhaps more accurately as is) but still allow receivers to be notified of changes.  Currently we need to add in at least a auth failed event, but as you know events could be added for any other events if necessary.

Also if you accept this patch or if we can work on a mutually agreeable solution you stand to gain from the man hours that both Tom and I have already expended on this, as well as the work of our QA team who will begin testing the changes in our branch very shortly.  Giving the changes in this patch much greater test exposure in a shorter amount of time than any of us could do ourselves. 

If you want we could sit down and perhaps do a conference call or a webinar where we could perhaps talk about the changes that have been made to the code revolving around sessions, perhaps explain some of the changes that were made and why they were made, answer any questions and to talk about ways we could possibly get this merged.  

Please feel free to PM or e-mail me anytime.

Brian

**Comment by fritzy** [comment]
Your arguments have convinced me to reconsider.  I'm working on some experiments right now with your state machine.  I understand that what we had before was more of a state manager than a state machine, and to be honest, I need both. stream:features handling right now is a mess, and could use some state machine and state management features.

**Comment by thom-nic** [comment]
Thanks.  Whatever we can do to help.

Can you explain the problem(s) with stream:features?  Is there a separate issue that details that?

**Comment by fritzy** [comment]
Issue #39

**Comment by fritzy** [comment]
done
