### ISSUE TITLE
XEP-0030 appears to fail to respond to discovery requests through the default handler

### ISSUE THREAD

**Issue by dannmartens** [fritzy/SleekXMPP#78]
The default 'disco_info' handler checks if another handler has been registered before it does its work. 

It does this by calling self.xmpp.event_handled('disco_info_request'), which returns '1' if only the default handler has been installed. However, the check assumes a '0' to be returned in that case.

As a result there is no default behaviour, and discovery agents time out waiting for a (default) response.

**Comment by legastero** [comment]
Ah, yes. This was fixed in develop a while ago, but the fix is not in the latest beta yet. You can use commit 291b118aca29b32679f1b2e55d0de98918fe4455 to correct the behavior.

There is a new version of the XEP-0030 plugin in the develop branch now that you may be interested in as well that does a much better job of doing dynamic disco responses.
