### ISSUE TITLE
What should be the correct behaviour for logins which don't match the server domain?

### ISSUE THREAD

**Issue by dannmartens** [fritzy/SleekXMPP#91]
Hi All,

After reading the documentation of XEP-0030, we were wondering if there could or should be a solution to the following problem.

If an attempt is made by Sleek to log in with a JID tied to domain 'alpha', to a server with domain 'omega', the final bound JID shows that the domain gets overridden as well (using Openfire).
We've noticed that this domain override interferes with the Disco configuration.

Features and identities added using the global dynamic handler are lost, once the binding has occured.

We're not sure if this case should be considered 'pathological'.

From the XEP-0030 documentation, there are three configuration scopes defined: 'global', 'jid' and 'node'. We would expect that 'global' scope configuration would not be impacted by any binding overrides.

Your feedback would be appreciated!

Cheers,
 Dann

**Comment by legastero** [comment]
Is this also using the default static disco implementation? If so, that would be where the issue is occurring, since the current self.boundjid is used to create JID/node key pairs to store and lookup disco data. Using the boundjid object itself instead of boundjid.full may resolve the issue, but will need to test that.

I would consider this to be an unusual and unexpected case at least. That the username and domain of the JID is constant is an assumption Sleek has made so far.

One solution would be to not add any disco entries until after the session_start event has fired so that the correct JID is used.
